/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsocketRouteImport } from './routes/websocket'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as MailRouteImport } from './routes/mail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ErrorLogsRouteImport } from './routes/error-logs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'

const WebsocketRoute = WebsocketRouteImport.update({
  id: '/websocket',
  path: '/websocket',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorLogsRoute = ErrorLogsRouteImport.update({
  id: '/error-logs',
  path: '/error-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/error-logs': typeof ErrorLogsRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/not-found': typeof NotFoundRoute
  '/permissions': typeof PermissionsRoute
  '/roles': typeof RolesRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/websocket': typeof WebsocketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/error-logs': typeof ErrorLogsRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/not-found': typeof NotFoundRoute
  '/permissions': typeof PermissionsRoute
  '/roles': typeof RolesRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/websocket': typeof WebsocketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/error-logs': typeof ErrorLogsRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/not-found': typeof NotFoundRoute
  '/permissions': typeof PermissionsRoute
  '/roles': typeof RolesRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/websocket': typeof WebsocketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/audit-logs'
    | '/dashboard'
    | '/error-logs'
    | '/files'
    | '/login'
    | '/mail'
    | '/not-found'
    | '/permissions'
    | '/roles'
    | '/setup'
    | '/users'
    | '/websocket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/audit-logs'
    | '/dashboard'
    | '/error-logs'
    | '/files'
    | '/login'
    | '/mail'
    | '/not-found'
    | '/permissions'
    | '/roles'
    | '/setup'
    | '/users'
    | '/websocket'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/audit-logs'
    | '/dashboard'
    | '/error-logs'
    | '/files'
    | '/login'
    | '/mail'
    | '/not-found'
    | '/permissions'
    | '/roles'
    | '/setup'
    | '/users'
    | '/websocket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuditLogsRoute: typeof AuditLogsRoute
  DashboardRoute: typeof DashboardRoute
  ErrorLogsRoute: typeof ErrorLogsRoute
  FilesRoute: typeof FilesRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRoute
  NotFoundRoute: typeof NotFoundRoute
  PermissionsRoute: typeof PermissionsRoute
  RolesRoute: typeof RolesRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
  WebsocketRoute: typeof WebsocketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websocket': {
      id: '/websocket'
      path: '/websocket'
      fullPath: '/websocket'
      preLoaderRoute: typeof WebsocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-logs': {
      id: '/error-logs'
      path: '/error-logs'
      fullPath: '/error-logs'
      preLoaderRoute: typeof ErrorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuditLogsRoute: AuditLogsRoute,
  DashboardRoute: DashboardRoute,
  ErrorLogsRoute: ErrorLogsRoute,
  FilesRoute: FilesRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRoute,
  NotFoundRoute: NotFoundRoute,
  PermissionsRoute: PermissionsRoute,
  RolesRoute: RolesRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
  WebsocketRoute: WebsocketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
